version: "2"
services:
  phantomjs:
    image: wernight/phantomjs:2
    ports:
      - "8910:8910"
    volumes: 
      - .:/app
    command: phantomjs --proxy=10.0.2.2:1080 --proxy-type=socks5 --webdriver=8910
  scrapy:
    build:
     context: .
     dockerfile: Dockerfile
    volumes: 
      - .:/app
    working_dir: /app
    depends_on: 
      - phantomjs
  phantomjs-vps:
    image: wernight/phantomjs:2
    ports:
      - "8910:8910"
    volumes: 
      - .:/app
    command: phantomjs --webdriver=8910
  scrapy-vps:
    build:
      context: .
      dockerfile: Dockerfile.vps
    volumes: 
      - .:/app
    working_dir: /app
    depends_on: 
      - phantomjs-vps
