version: "3"
services:
  crawler:
    build:
      context: https://github.com/gas1121/scrapy-cluster.git#py3
      dockerfile: docker/crawler/Dockerfile.py3
    depends_on:
      - kafka
      - redis
      - zookeeper
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always
  postgres:
    image: library/postgres:alpine
    expose:
      - "5432"
    volumes:
      - pgdata:${PGDATA:-/var/lib/postgresql/data}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-japancinemastatus}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-japancinemastatus}
      - POSTGRES_DB=${POSTGRES_DB:-japancinemastatus}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
  psql:
    image: library/postgres:alpine
    command: psql -h postgres -p 5432 -U ${POSTGRES_USER:-japancinemastatus} -W ${POSTGRES_PASSWORD:-japancinemastatus}
  pgweb:
    image: sosedoff/pgweb
    depends_on: 
      - postgres
    ports: 
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-japancinemastatus}:${POSTGRES_PASSWORD:-japancinemastatus}@postgres:5432/${POSTGRES_DB:-japancinemastatus}?sslmode=disable
  phantomjs:
    image: wernight/phantomjs:2
    expose:
      - "8910"
    volumes: 
      - .:/app
    command: phantomjs --proxy=${PROXY_ADDRESS:-10.0.2.2}:${PROXY_PORT:-1080} --proxy-type=${PROXY_TYPE:-socks5} --webdriver=8910
  redis:
    image: library/redis:alpine
    expose:
      - "6379"
    volumes:
      - redisdata:${PGWEB_PORT:-/data}
    restart: always
  scrapy:
    build:
     context: .
     dockerfile: Dockerfile
     args:
       - USE_MIRROR:${USE_MIRROR:-0}
    volumes: 
      - .:/app
    working_dir: /app
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-japancinemastatus}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-japancinemastatus}
      - POSTGRES_DB=${POSTGRES_DB:-japancinemastatus}
      - PROXY_ADDRESS=${PROXY_ADDRESS:-10.0.2.2}
      - PROXY_PORT=${PROXY_PORT:-1080}
      - PROXY_TYPE=${PROXY_TYPE:-socks5}
    depends_on: 
      - postgres
      - redis
    command: python run.py
volumes:
  pgdata:
  redisdata:
