version: "3"
services:
  utils:
    build:
      context: .
      dockerfile: ./docker/utils/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    volumes: 
      - ./utils:/app
    working_dir: /app
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  crawler:
    build:
      context: .
      dockerfile: ./docker/crawler/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: 127.0.0.1:5000/japancinemastatusspider:crawler
    volumes: 
      - ./crawler:/app
    working_dir: /app
    depends_on:
      - kafka
      - redis
      - zookeeper
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PROXY_ADDRESS=${PROXY_ADDRESS:-10.0.2.2}
      - PROXY_PORT=${PROXY_PORT:-1080}
      - PROXY_TYPE=${PROXY_TYPE:-socks5}
    command: scrapy crawl --all_spiders
  scheduler:
    build:
      context: .
      dockerfile: ./docker/scheduler/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: 127.0.0.1:5000/japancinemastatusspider:scheduler
    environment:
      ZOOKEEPER_HOST: zookeeper:2181
      JS_ZOOKEEPER_PATH: /japancinemastatusspider/spiders/
      JS_ZOOKEEPER_ID: all
    volumes: 
      - ./scheduler:/app
    working_dir: /app
    depends_on:
      - kafka
      - redis
      - zookeeper
  data_processor:
    build:
      context: .
      dockerfile: ./docker/data_processor/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: 127.0.0.1:5000/japancinemastatusspider:data_processor
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - ./data_processor:/app
    working_dir: /app
    depends_on:
      - kafka
      - redis
      - zookeeper
      - postgres
    restart: always
  kafka_monitor:
    build:
      context: .
      dockerfile: ./docker/kafka_monitor/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: 127.0.0.1:5000/japancinemastatusspider:kafka_monitor
    depends_on:
      - kafka
      - redis
    restart: always
  redis_monitor:
    build:
      context: .
      dockerfile: ./docker/redis_monitor/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: 127.0.0.1:5000/japancinemastatusspider:redis_monitor
    depends_on:
      - kafka
      - redis
      - zookeeper
    restart: always
  rest:
    build:
      context: .
      dockerfile: ./docker/rest/Dockerfile
      args:
        - USE_MIRROR=${USE_MIRROR:-0}
    image: 127.0.0.1:5000/japancinemastatusspider:rest
    depends_on:
      - kafka
      - redis
    restart: always
    ports:
      - "8888:5343"
  zookeeper:
    image: zookeeper
    expose:
      - "2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always
  postgres:
    image: library/postgres:alpine
    expose:
      - "5432"
    volumes:
      - pgdata:${PGDATA:-/var/lib/postgresql/data}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data}
  psql:
    image: library/postgres:alpine
    command: psql -h postgres -p 5432 -U ${POSTGRES_USER} -W ${POSTGRES_PASSWORD}
  pgweb:
    image: sosedoff/pgweb
    depends_on: 
      - postgres
    ports: 
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
  phantomjs:
    image: wernight/phantomjs:2
    expose:
      - "8910"
    volumes: 
      - .:/app
    command: phantomjs --proxy=${PROXY_ADDRESS:-10.0.2.2}:${PROXY_PORT:-1080} --proxy-type=${PROXY_TYPE:-socks5} --webdriver=8910
  redis:
    image: library/redis:alpine
    expose:
      - "6379"
    volumes:
      - redisdata:${PGWEB_PORT:-/data}
    restart: always
volumes:
  pgdata:
  redisdata:
