version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    command: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m"
      - bootstrap.memory_lock=true
      - discovery.zen.minimum_master_nodes=1
      - network.host=0.0.0.0
      - xpack.security.enabled=false
    expose:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 650M
        reservations:
          memory: 550M
  logstash:
    build:
      context: .
      dockerfile: ./Dockerfile.logstash
    image: 127.0.0.1:5000/japancinemastatusspider:logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    environment:
      - "LS_JAVA_OPTS=-Xms100m -Xmx400m"
    volumes:
      - logs:/var/log/scrapy-cluster
    expose:
      - "5000"
    depends_on:
      - elasticsearch
    deploy:
      mode: global
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 60s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 300M
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    environment:
      - xpack.security.enabled=false
    ports:
      - "9090:5601"
    depends_on:
      - elasticsearch
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 60s
volumes:
  logs:
    external:
      name: jcss_logs
