version: "3"
services:
  crawler:
    image: gas1121/japancinemastatusspider:crawler-test
    depends_on:
      - kafka
      - redis
      - zookeeper
  scheduler:
    image: gas1121/japancinemastatusspider:scheduler-test
    depends_on:
      - kafka
      - redis
      - zookeeper
  redis:
    image: redis
    ports:
      - "6379"
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always
