version: "3"
services:
  utils:
    image: gas1121/japancinemastatusspider:utils-test
    depends_on:
      - postgres
    command: ping localhost
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=testdefault
  crawler:
    image: gas1121/japancinemastatusspider:crawler-test
    depends_on:
      - kafka
      - redis
      - zookeeper
      - postgres
    command: ping localhost
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=testdefault
  scheduler:
    image: gas1121/japancinemastatusspider:scheduler-test
    depends_on:
      - kafka
      - redis
      - zookeeper
    command: ping localhost
  data_processor:
    image: gas1121/japancinemastatusspider:data_processor-test
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=testdefault
    command: ping localhost
    depends_on:
      - kafka
      - redis
      - zookeeper
      - postgres
  redis:
    image: redis
    ports:
      - "6379"
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always
  postgres:
    image: library/postgres:alpine
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=testdefault
